#!/usr/bin/env php
<?php

chdir(__DIR__);

# Composer 環境
shell_exec('composer install');

# 引入宣告檔
require_once 'declarations.php';

# 在 storage 目錄下建立必需的資料夾
$directories = require_once 'directories.php';
foreach ($directories as $directory)
{
    if (!is_dir($directory) && !is_file($directory)) mkdir($directory);
}

# 引入設定檔產生器
require_once STORAGE_DIR . DIRECTORY_SEPARATOR . 'configs' . DIRECTORY_SEPARATOR . 'codes' . DIRECTORY_SEPARATOR . 'generator.php';

# 產生玩家資料 PHP 設定檔
buildPlayerConfig();

# 產生 Telegram 機器人 PHP 設定檔
buildTelegramBotConfig();
